# Generated by Django 4.0.1 on 2022-01-23 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='play')),
                ('level', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'play_image',
            },
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('image', models.ImageField(upload_to='tile')),
                ('is_blank', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='app.playimage')),
            ],
            options={
                'db_table': 'tile',
            },
        ),
    ]
