# Generated by Django 4.0.1 on 2022-01-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='test',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
