# Generated by Django 4.0.1 on 2022-01-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_tile_is_blank_remove_tile_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='is_blank',
            field=models.BooleanField(default=False),
        ),
    ]
