# Generated by Django 4.0.1 on 2022-01-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_image_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PlayImage',
        ),
    ]
