# Generated by Django 4.0.1 on 2022-01-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tile_is_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='new_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tile',
            name='new_y',
            field=models.IntegerField(default=0),
        ),
    ]
