# Generated by Django 4.0.1 on 2022-01-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tile_new_x_tile_new_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
