# Generated by Django 4.0.1 on 2022-01-23 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_tile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('success', models.BooleanField(default=False)),
                ('play_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_image', to='app.playimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.RemoveField(
            model_name='tile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='new_x',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='new_y',
        ),
        migrations.CreateModel(
            name='GameTile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_x', models.IntegerField(default=0)),
                ('current_y', models.IntegerField(default=0)),
                ('name', models.TextField(default='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='app.game')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tile', to='app.tile')),
            ],
            options={
                'db_table': 'gametile',
            },
        ),
    ]
