# Generated by Django 4.0.1 on 2022-01-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tile_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameTile',
        ),
    ]
