# Generated by Django 4.0.1 on 2022-01-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_gametile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='index',
        ),
    ]
